title: "Submit64-Vue"
description: "Documentation"
theme: just-the-docs
markdown: kramdown
color_scheme: dark
baseurl: "/Submit64-Vue"
mermaid:
  version: "9.1.3"
callouts:
  warning:
    title: Attention
    color: red
  important:
    title: Important
    color: blue
  highlight:
    color: yellow
  new:
    title: Nouveau
    color: green
  note:
    title: Note
    color: purple
